# Generated by Django 3.1.1 on 2020-10-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuelength', '0004_store_queue_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_queue',
            name='threshold',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='store_queue',
            name='threshold_duration',
            field=models.DurationField(null=True),
        ),
    ]
