# Generated by Django 3.1.1 on 2020-10-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuelength', '0005_auto_20201003_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_queue',
            name='threshold',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='store_queue',
            name='threshold_duration',
            field=models.DurationField(),
        ),
    ]
