# Generated by Django 3.1.1 on 2020-10-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuelength', '0006_auto_20201004_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_queue',
            name='threshold',
            field=models.IntegerField(),
        ),
    ]
